spring:
  application:
    name: ReviewService
  datasource:
    url: jdbc:postgresql://localhost:5435/reviewservice-db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect




server:
  port: 8086


eureka:
  client:
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10



logging:
  level:
    root: INFO
#    root: DEBUG