## Используем официальный образ Nginx для сервировки статического контента
#FROM nginx:alpine
#
## Копируем статические файлы (HTML, CSS) в директорию, обслуживаемую Nginx
#COPY ./static /usr/share/nginx/html
#
## Открываем порт для доступа к фронтенду
#EXPOSE 8085
#
## Запускаем Nginx
#CMD ["nginx", "-g", "daemon off;"]
