server:
  port: 8761
spring:
  application:
    name: EurekaServer

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka


  server:
    renewal-percent-threshold: 0.5
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: true
