server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: lb://AuthService
          predicates:
            - Path=/serviceAuth/**
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/api/products/**
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/serviceOrder/**
        - id: FrontendService
          uri: lb://FrontendService
          predicates:
            - Path=/products/**, /products/add/**

  application:
    name: GateWay

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/


eureka:
  client:
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

