server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: lb://AuthService
          predicates:
            - Path=/auth/**
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/products/**
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/orders/**
        - id: ReviewService
          uri: lb://ReviewService
          predicates:
            - Path=/reviews/**


      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8085"  # Домен фронтенда
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
  application:
    name: GateWay

logging:
  level:
    root: DEBUG



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

