server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: lb://AuthService
          predicates:
            - Path=/serviceAuth/**
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/serviceProduct/**
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/serviceOrder/**



  application:
    name: GateWay

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
