spring:
  application:
    name: AuthService
  datasource:
    url: jdbc:postgresql://localhost:5432/authservice-db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Автоматическое обновление схемы БД
    show-sql: true  # Показать SQL-запросы в логах
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Платформа PostgreSQL для Hibernate

server:
  port: 8081  # Порт, на котором будет работать сервис
logging:
  level:
    root: DEBUG
eureka:
  client:
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

