server:
  port: 8081
spring:
  application:
    name: AuthService


  datasource:
    url: jdbc:postgresql://localhost:5432/authservice
    username: admin
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update



