server:
  port: 8085

spring:
  web:
    resources:
      static-locations: classpath:/static/
  application:
    name: FrontendService

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


gateway:
  url: http://localhost:8765  # URL для Gateway