spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:postgresql://localhost:5434/orderservice-db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083