spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:postgresql://localhost:5434/orderservice-db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083
logging:
  level:
    root: INFO
eureka:
  client:
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

gateway:
  url: http://localhost:8765  # URL для Gateway

